### ISSUE TITLE
Problems logging into netbird

### ISSUE THREAD

**Issue by PBXForums** [totmicro/helms#14]
Every so often I get an error when trying to reauthenticate to netbird.

In the logs I see this kind of thing:
ERRO management/client/grpc.go:278: failed while getting Management Service public key: rpc error: code = Unavailable desc = unexpected HTTP status code received from server: 502 (Bad Gateway); transport: received unexpected content-type "text/html"
2024-11-13T16:18:02Z ERRO client/internal/login.go:105: failed while getting Management Service public key: failed while getting Management Service public key
2024-11-13T16:18:02Z ERRO client/server/server.go:277: failed login: failed while getting Management Service public key

After a short time, logging in again is successful.

The only thing I have managed to find when googling this is: https://github.com/kubernetes/ingress-nginx/issues/4836

I'm not sure if that is completely irrelevant.

**Comment by marcportabellaclotet-mt** [comment]
The issue is likely on the Netbird side. I’ve added an option to enable the backward-compatible gRPC management port. To use this, upgrade to chart version v1.5.3 or higher and set the following:

```yaml
management:
  useBackwardsGrpcService: true
```

This will create a dedicated service for the management gRPC, and the management grpc ingress will be configured to point to it.

**Comment by PBXForums** [comment]
Thank you, I would just like to add that I have been monitoring and this does appear to have resolved my issue.
